### ISSUE TITLE
Issue saving notes

### ISSUE THREAD

**Issue by frcamacho** [tnguyen14/notes#21]
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
/notes/#:1 Fetch API cannot load https://api.tridnguyen.com/notes/drive. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://lab.tridnguyen.com' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.js:796 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined(…)

**Comment by tnguyen14** [comment]
Oh no! that's super bad.

Do you see it happen after refresh? I do seem to see it intermittently, but can't quite reproduce it.

**Comment by tnguyen14** [comment]
Can you try this again? I've made a few updates that might have solved this.

**Comment by tnguyen14** [comment]
Closing for now. If you can reproduce it, let me know.
